sudo: required
services:
  - docker

before_install:
  - docker build -t darrellsnow/node-frontend -f Dockerfile.dev .

script:
  - docker run -e CI=true darrellsnow/node-frontend npm run test

deploy:
  provider: elasticbeanstalk
  region: "ca-central-1"
  app: "node-frontend"
  bucket_name: "elasticbeanstalk-ca-central-1-180405251853"
  bucket_path: "node-frontend"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: "$AWS_SECRET_KEY"